# Generated by Django 5.1.1 on 2024-09-29 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("content_type", models.CharField()),
                ("charset", models.CharField(blank=True, null=True)),
                (
                    "visibility",
                    models.CharField(
                        choices=[("public", "public"), ("private", "private")],
                        default="public",
                    ),
                ),
                ("size", models.IntegerField()),
                ("location", models.CharField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("posts", models.ManyToManyField(to="blog.post")),
            ],
        ),
    ]
