# Generated by Django 5.1.1 on 2024-10-11 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_alter_comment_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="reviewed",
            field=models.BooleanField(default=False),
        ),
    ]
