/* tslint:disable */
/* eslint-disable */
/**
 * ooo-yay.com API
 * Resource-based API for ooo-yay.com.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PostDetails } from './PostDetails';
import {
    PostDetailsFromJSON,
    PostDetailsFromJSONTyped,
    PostDetailsToJSON,
} from './PostDetails';
import type { AuthorSummary } from './AuthorSummary';
import {
    AuthorSummaryFromJSON,
    AuthorSummaryFromJSONTyped,
    AuthorSummaryToJSON,
} from './AuthorSummary';

/**
 * 
 * @export
 * @interface AdminParentCommentList
 */
export interface AdminParentCommentList {
    /**
     * 
     * @type {number}
     * @memberof AdminParentCommentList
     */
    id: number;
    /**
     * 
     * @type {AuthorSummary}
     * @memberof AdminParentCommentList
     */
    author: AuthorSummary;
    /**
     * 
     * @type {string}
     * @memberof AdminParentCommentList
     */
    content: string;
    /**
     * 
     * @type {PostDetails}
     * @memberof AdminParentCommentList
     */
    post: PostDetails;
    /**
     * 
     * @type {AdminParentCommentList}
     * @memberof AdminParentCommentList
     */
    parent?: AdminParentCommentList | null;
    /**
     * 
     * @type {boolean}
     * @memberof AdminParentCommentList
     */
    visible: boolean;
    /**
     * 
     * @type {Date}
     * @memberof AdminParentCommentList
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof AdminParentCommentList
     */
    updatedAt: Date;
    /**
     * 
     * @type {boolean}
     * @memberof AdminParentCommentList
     */
    reviewed: boolean;
    /**
     * 
     * @type {string}
     * @memberof AdminParentCommentList
     */
    note?: string | null;
}

/**
 * Check if a given object implements the AdminParentCommentList interface.
 */
export function instanceOfAdminParentCommentList(value: object): value is AdminParentCommentList {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('author' in value) || value['author'] === undefined) return false;
    if (!('content' in value) || value['content'] === undefined) return false;
    if (!('post' in value) || value['post'] === undefined) return false;
    if (!('visible' in value) || value['visible'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('reviewed' in value) || value['reviewed'] === undefined) return false;
    return true;
}

export function AdminParentCommentListFromJSON(json: any): AdminParentCommentList {
    return AdminParentCommentListFromJSONTyped(json, false);
}

export function AdminParentCommentListFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminParentCommentList {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'author': AuthorSummaryFromJSON(json['author']),
        'content': json['content'],
        'post': PostDetailsFromJSON(json['post']),
        'parent': json['parent'] == null ? undefined : AdminParentCommentListFromJSON(json['parent']),
        'visible': json['visible'],
        'createdAt': (new Date(json['created_at'])),
        'updatedAt': (new Date(json['updated_at'])),
        'reviewed': json['reviewed'],
        'note': json['note'] == null ? undefined : json['note'],
    };
}

export function AdminParentCommentListToJSON(value?: AdminParentCommentList | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'author': AuthorSummaryToJSON(value['author']),
        'content': value['content'],
        'post': PostDetailsToJSON(value['post']),
        'parent': AdminParentCommentListToJSON(value['parent']),
        'visible': value['visible'],
        'created_at': ((value['createdAt']).toISOString()),
        'updated_at': ((value['updatedAt']).toISOString()),
        'reviewed': value['reviewed'],
        'note': value['note'],
    };
}

