/* tslint:disable */
/* eslint-disable */
/**
 * ooo-yay.com API
 * Resource-based API for ooo-yay.com.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AdminCommentUpdate
 */
export interface AdminCommentUpdate {
    /**
     * 
     * @type {boolean}
     * @memberof AdminCommentUpdate
     */
    visible?: boolean | null;
    /**
     * 
     * @type {string}
     * @memberof AdminCommentUpdate
     */
    note?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof AdminCommentUpdate
     */
    reviewed: boolean;
}

/**
 * Check if a given object implements the AdminCommentUpdate interface.
 */
export function instanceOfAdminCommentUpdate(value: object): value is AdminCommentUpdate {
    if (!('reviewed' in value) || value['reviewed'] === undefined) return false;
    return true;
}

export function AdminCommentUpdateFromJSON(json: any): AdminCommentUpdate {
    return AdminCommentUpdateFromJSONTyped(json, false);
}

export function AdminCommentUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminCommentUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'visible': json['visible'] == null ? undefined : json['visible'],
        'note': json['note'] == null ? undefined : json['note'],
        'reviewed': json['reviewed'],
    };
}

export function AdminCommentUpdateToJSON(value?: AdminCommentUpdate | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'visible': value['visible'],
        'note': value['note'],
        'reviewed': value['reviewed'],
    };
}

