/* tslint:disable */
/* eslint-disable */
/**
 * ooo-yay.com API
 * Resource-based API for ooo-yay.com.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AdminParentCommentList } from './AdminParentCommentList';
import {
    AdminParentCommentListFromJSON,
    AdminParentCommentListFromJSONTyped,
    AdminParentCommentListToJSON,
} from './AdminParentCommentList';
import type { PostDetails } from './PostDetails';
import {
    PostDetailsFromJSON,
    PostDetailsFromJSONTyped,
    PostDetailsToJSON,
} from './PostDetails';
import type { AuthorSummary } from './AuthorSummary';
import {
    AuthorSummaryFromJSON,
    AuthorSummaryFromJSONTyped,
    AuthorSummaryToJSON,
} from './AuthorSummary';
import type { AdminChildCommentList } from './AdminChildCommentList';
import {
    AdminChildCommentListFromJSON,
    AdminChildCommentListFromJSONTyped,
    AdminChildCommentListToJSON,
} from './AdminChildCommentList';

/**
 * 
 * @export
 * @interface AdminCommentList
 */
export interface AdminCommentList {
    /**
     * 
     * @type {number}
     * @memberof AdminCommentList
     */
    id: number;
    /**
     * 
     * @type {AuthorSummary}
     * @memberof AdminCommentList
     */
    author: AuthorSummary;
    /**
     * 
     * @type {string}
     * @memberof AdminCommentList
     */
    content: string;
    /**
     * 
     * @type {PostDetails}
     * @memberof AdminCommentList
     */
    post: PostDetails;
    /**
     * 
     * @type {Array<AdminChildCommentList>}
     * @memberof AdminCommentList
     */
    children?: Array<AdminChildCommentList> | null;
    /**
     * 
     * @type {AdminParentCommentList}
     * @memberof AdminCommentList
     */
    parent?: AdminParentCommentList | null;
    /**
     * 
     * @type {boolean}
     * @memberof AdminCommentList
     */
    visible: boolean;
    /**
     * 
     * @type {Date}
     * @memberof AdminCommentList
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof AdminCommentList
     */
    updatedAt: Date;
    /**
     * 
     * @type {boolean}
     * @memberof AdminCommentList
     */
    reviewed: boolean;
    /**
     * 
     * @type {string}
     * @memberof AdminCommentList
     */
    note?: string | null;
}

/**
 * Check if a given object implements the AdminCommentList interface.
 */
export function instanceOfAdminCommentList(value: object): value is AdminCommentList {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('author' in value) || value['author'] === undefined) return false;
    if (!('content' in value) || value['content'] === undefined) return false;
    if (!('post' in value) || value['post'] === undefined) return false;
    if (!('visible' in value) || value['visible'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('reviewed' in value) || value['reviewed'] === undefined) return false;
    return true;
}

export function AdminCommentListFromJSON(json: any): AdminCommentList {
    return AdminCommentListFromJSONTyped(json, false);
}

export function AdminCommentListFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminCommentList {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'author': AuthorSummaryFromJSON(json['author']),
        'content': json['content'],
        'post': PostDetailsFromJSON(json['post']),
        'children': json['children'] == null ? undefined : ((json['children'] as Array<any>).map(AdminChildCommentListFromJSON)),
        'parent': json['parent'] == null ? undefined : AdminParentCommentListFromJSON(json['parent']),
        'visible': json['visible'],
        'createdAt': (new Date(json['created_at'])),
        'updatedAt': (new Date(json['updated_at'])),
        'reviewed': json['reviewed'],
        'note': json['note'] == null ? undefined : json['note'],
    };
}

export function AdminCommentListToJSON(value?: AdminCommentList | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'author': AuthorSummaryToJSON(value['author']),
        'content': value['content'],
        'post': PostDetailsToJSON(value['post']),
        'children': value['children'] == null ? undefined : ((value['children'] as Array<any>).map(AdminChildCommentListToJSON)),
        'parent': AdminParentCommentListToJSON(value['parent']),
        'visible': value['visible'],
        'created_at': ((value['createdAt']).toISOString()),
        'updated_at': ((value['updatedAt']).toISOString()),
        'reviewed': value['reviewed'],
        'note': value['note'],
    };
}

