/* tslint:disable */
/* eslint-disable */
/**
 * ooo-yay.com API
 * Resource-based API for ooo-yay.com.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Attachment
 */
export interface Attachment {
    /**
     * The URL of the attachment
     * @type {string}
     * @memberof Attachment
     */
    url: string;
    /**
     * The MIME type of the attachment
     * @type {string}
     * @memberof Attachment
     */
    mimeType: string;
    /**
     * 
     * @type {string}
     * @memberof Attachment
     */
    title?: string | null;
    /**
     * 
     * @type {number}
     * @memberof Attachment
     */
    sizeInBytes?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Attachment
     */
    durationInSeconds?: number | null;
}

/**
 * Check if a given object implements the Attachment interface.
 */
export function instanceOfAttachment(value: object): value is Attachment {
    if (!('url' in value) || value['url'] === undefined) return false;
    if (!('mimeType' in value) || value['mimeType'] === undefined) return false;
    return true;
}

export function AttachmentFromJSON(json: any): Attachment {
    return AttachmentFromJSONTyped(json, false);
}

export function AttachmentFromJSONTyped(json: any, ignoreDiscriminator: boolean): Attachment {
    if (json == null) {
        return json;
    }
    return {
        
        'url': json['url'],
        'mimeType': json['mime_type'],
        'title': json['title'] == null ? undefined : json['title'],
        'sizeInBytes': json['size_in_bytes'] == null ? undefined : json['size_in_bytes'],
        'durationInSeconds': json['duration_in_seconds'] == null ? undefined : json['duration_in_seconds'],
    };
}

export function AttachmentToJSON(value?: Attachment | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'url': value['url'],
        'mime_type': value['mimeType'],
        'title': value['title'],
        'size_in_bytes': value['sizeInBytes'],
        'duration_in_seconds': value['durationInSeconds'],
    };
}

