/* tslint:disable */
/* eslint-disable */
/**
 * ooo-yay.com API
 * Resource-based API for ooo-yay.com.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthorSummary
 */
export interface AuthorSummary {
    /**
     * 
     * @type {number}
     * @memberof AuthorSummary
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof AuthorSummary
     */
    username: string;
}

/**
 * Check if a given object implements the AuthorSummary interface.
 */
export function instanceOfAuthorSummary(value: object): value is AuthorSummary {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('username' in value) || value['username'] === undefined) return false;
    return true;
}

export function AuthorSummaryFromJSON(json: any): AuthorSummary {
    return AuthorSummaryFromJSONTyped(json, false);
}

export function AuthorSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthorSummary {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'username': json['username'],
    };
}

export function AuthorSummaryToJSON(value?: AuthorSummary | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'username': value['username'],
    };
}

