/* tslint:disable */
/* eslint-disable */
/**
 * ooo-yay.com API
 * Resource-based API for ooo-yay.com.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Schema for creating and updating groups
 * @export
 * @interface GroupMutate
 */
export interface GroupMutate {
    /**
     * 
     * @type {string}
     * @memberof GroupMutate
     */
    name: string;
    /**
     * 
     * @type {Array<number>}
     * @memberof GroupMutate
     */
    permissions?: Array<number> | null;
}

/**
 * Check if a given object implements the GroupMutate interface.
 */
export function instanceOfGroupMutate(value: object): value is GroupMutate {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function GroupMutateFromJSON(json: any): GroupMutate {
    return GroupMutateFromJSONTyped(json, false);
}

export function GroupMutateFromJSONTyped(json: any, ignoreDiscriminator: boolean): GroupMutate {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'permissions': json['permissions'] == null ? undefined : json['permissions'],
    };
}

export function GroupMutateToJSON(value?: GroupMutate | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'permissions': value['permissions'],
    };
}

