/* tslint:disable */
/* eslint-disable */
/**
 * ooo-yay.com API
 * Resource-based API for ooo-yay.com.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const HealthStatus = {
    Ok: 'ok',
    NotOk: 'not_ok'
} as const;
export type HealthStatus = typeof HealthStatus[keyof typeof HealthStatus];


export function instanceOfHealthStatus(value: any): boolean {
    for (const key in HealthStatus) {
        if (Object.prototype.hasOwnProperty.call(HealthStatus, key)) {
            if ((HealthStatus as Record<string, HealthStatus>)[key] === value) {
                return true;
            }
        }
    }
    return false;
}

export function HealthStatusFromJSON(json: any): HealthStatus {
    return HealthStatusFromJSONTyped(json, false);
}

export function HealthStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): HealthStatus {
    return json as HealthStatus;
}

export function HealthStatusToJSON(value?: HealthStatus | null): any {
    return value as any;
}

