/* tslint:disable */
/* eslint-disable */
/**
 * ooo-yay.com API
 * Resource-based API for ooo-yay.com.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Hub
 */
export interface Hub {
    /**
     * The type of the hub.
     * @type {string}
     * @memberof Hub
     */
    type: string;
    /**
     * The URL of the hub.
     * @type {string}
     * @memberof Hub
     */
    url: string;
}

/**
 * Check if a given object implements the Hub interface.
 */
export function instanceOfHub(value: object): value is Hub {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('url' in value) || value['url'] === undefined) return false;
    return true;
}

export function HubFromJSON(json: any): Hub {
    return HubFromJSONTyped(json, false);
}

export function HubFromJSONTyped(json: any, ignoreDiscriminator: boolean): Hub {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'url': json['url'],
    };
}

export function HubToJSON(value?: Hub | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'type': value['type'],
        'url': value['url'],
    };
}

