/* tslint:disable */
/* eslint-disable */
/**
 * ooo-yay.com API
 * Resource-based API for ooo-yay.com.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MultiPartBodyParamsPostsInner
 */
export interface MultiPartBodyParamsPostsInner {
}

/**
 * Check if a given object implements the MultiPartBodyParamsPostsInner interface.
 */
export function instanceOfMultiPartBodyParamsPostsInner(value: object): value is MultiPartBodyParamsPostsInner {
    return true;
}

export function MultiPartBodyParamsPostsInnerFromJSON(json: any): MultiPartBodyParamsPostsInner {
    return MultiPartBodyParamsPostsInnerFromJSONTyped(json, false);
}

export function MultiPartBodyParamsPostsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): MultiPartBodyParamsPostsInner {
    return json;
}

export function MultiPartBodyParamsPostsInnerToJSON(value?: MultiPartBodyParamsPostsInner | null): any {
    return value;
}

