/* tslint:disable */
/* eslint-disable */
/**
 * ooo-yay.com API
 * Resource-based API for ooo-yay.com.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OrphanedFileDetails
 */
export interface OrphanedFileDetails {
    /**
     * 
     * @type {string}
     * @memberof OrphanedFileDetails
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof OrphanedFileDetails
     */
    size: number;
    /**
     * 
     * @type {string}
     * @memberof OrphanedFileDetails
     */
    contentType: string;
    /**
     * 
     * @type {string}
     * @memberof OrphanedFileDetails
     */
    location: string;
    /**
     * 
     * @type {Date}
     * @memberof OrphanedFileDetails
     */
    lastModified: Date | null;
    /**
     * 
     * @type {string}
     * @memberof OrphanedFileDetails
     */
    visibility: string;
}

/**
 * Check if a given object implements the OrphanedFileDetails interface.
 */
export function instanceOfOrphanedFileDetails(value: object): value is OrphanedFileDetails {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('size' in value) || value['size'] === undefined) return false;
    if (!('contentType' in value) || value['contentType'] === undefined) return false;
    if (!('location' in value) || value['location'] === undefined) return false;
    if (!('lastModified' in value) || value['lastModified'] === undefined) return false;
    if (!('visibility' in value) || value['visibility'] === undefined) return false;
    return true;
}

export function OrphanedFileDetailsFromJSON(json: any): OrphanedFileDetails {
    return OrphanedFileDetailsFromJSONTyped(json, false);
}

export function OrphanedFileDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrphanedFileDetails {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'size': json['size'],
        'contentType': json['content_type'],
        'location': json['location'],
        'lastModified': (json['last_modified'] == null ? null : new Date(json['last_modified'])),
        'visibility': json['visibility'],
    };
}

export function OrphanedFileDetailsToJSON(value?: OrphanedFileDetails | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'size': value['size'],
        'content_type': value['contentType'],
        'location': value['location'],
        'last_modified': (value['lastModified'] == null ? null : (value['lastModified'] as any).toISOString()),
        'visibility': value['visibility'],
    };
}

