/* tslint:disable */
/* eslint-disable */
/**
 * ooo-yay.com API
 * Resource-based API for ooo-yay.com.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OrphanedFileDetails } from './OrphanedFileDetails';
import {
    OrphanedFileDetailsFromJSON,
    OrphanedFileDetailsFromJSONTyped,
    OrphanedFileDetailsToJSON,
} from './OrphanedFileDetails';

/**
 * 
 * @export
 * @interface OrphanedFiles
 */
export interface OrphanedFiles {
    /**
     * 
     * @type {Array<OrphanedFileDetails>}
     * @memberof OrphanedFiles
     */
    _public: Array<OrphanedFileDetails>;
    /**
     * 
     * @type {Array<OrphanedFileDetails>}
     * @memberof OrphanedFiles
     */
    _private: Array<OrphanedFileDetails>;
}

/**
 * Check if a given object implements the OrphanedFiles interface.
 */
export function instanceOfOrphanedFiles(value: object): value is OrphanedFiles {
    if (!('_public' in value) || value['_public'] === undefined) return false;
    if (!('_private' in value) || value['_private'] === undefined) return false;
    return true;
}

export function OrphanedFilesFromJSON(json: any): OrphanedFiles {
    return OrphanedFilesFromJSONTyped(json, false);
}

export function OrphanedFilesFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrphanedFiles {
    if (json == null) {
        return json;
    }
    return {
        
        '_public': ((json['public'] as Array<any>).map(OrphanedFileDetailsFromJSON)),
        '_private': ((json['private'] as Array<any>).map(OrphanedFileDetailsFromJSON)),
    };
}

export function OrphanedFilesToJSON(value?: OrphanedFiles | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'public': ((value['_public'] as Array<any>).map(OrphanedFileDetailsToJSON)),
        'private': ((value['_private'] as Array<any>).map(OrphanedFileDetailsToJSON)),
    };
}

