/* tslint:disable */
/* eslint-disable */
/**
 * ooo-yay.com API
 * Resource-based API for ooo-yay.com.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PostDetails } from './PostDetails';
import {
    PostDetailsFromJSON,
    PostDetailsFromJSONTyped,
    PostDetailsToJSON,
} from './PostDetails';

/**
 * 
 * @export
 * @interface PagedPostDetails
 */
export interface PagedPostDetails {
    /**
     * 
     * @type {Array<PostDetails>}
     * @memberof PagedPostDetails
     */
    items: Array<PostDetails>;
    /**
     * 
     * @type {number}
     * @memberof PagedPostDetails
     */
    count: number;
}

/**
 * Check if a given object implements the PagedPostDetails interface.
 */
export function instanceOfPagedPostDetails(value: object): value is PagedPostDetails {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('count' in value) || value['count'] === undefined) return false;
    return true;
}

export function PagedPostDetailsFromJSON(json: any): PagedPostDetails {
    return PagedPostDetailsFromJSONTyped(json, false);
}

export function PagedPostDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): PagedPostDetails {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(PostDetailsFromJSON)),
        'count': json['count'],
    };
}

export function PagedPostDetailsToJSON(value?: PagedPostDetails | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'items': ((value['items'] as Array<any>).map(PostDetailsToJSON)),
        'count': value['count'],
    };
}

