/* tslint:disable */
/* eslint-disable */
/**
 * ooo-yay.com API
 * Resource-based API for ooo-yay.com.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SeriesPublic } from './SeriesPublic';
import {
    SeriesPublicFromJSON,
    SeriesPublicFromJSONTyped,
    SeriesPublicToJSON,
} from './SeriesPublic';

/**
 * 
 * @export
 * @interface PagedSeriesPublic
 */
export interface PagedSeriesPublic {
    /**
     * 
     * @type {Array<SeriesPublic>}
     * @memberof PagedSeriesPublic
     */
    items: Array<SeriesPublic>;
    /**
     * 
     * @type {number}
     * @memberof PagedSeriesPublic
     */
    count: number;
}

/**
 * Check if a given object implements the PagedSeriesPublic interface.
 */
export function instanceOfPagedSeriesPublic(value: object): value is PagedSeriesPublic {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('count' in value) || value['count'] === undefined) return false;
    return true;
}

export function PagedSeriesPublicFromJSON(json: any): PagedSeriesPublic {
    return PagedSeriesPublicFromJSONTyped(json, false);
}

export function PagedSeriesPublicFromJSONTyped(json: any, ignoreDiscriminator: boolean): PagedSeriesPublic {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(SeriesPublicFromJSON)),
        'count': json['count'],
    };
}

export function PagedSeriesPublicToJSON(value?: PagedSeriesPublic | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'items': ((value['items'] as Array<any>).map(SeriesPublicToJSON)),
        'count': value['count'],
    };
}

