/* tslint:disable */
/* eslint-disable */
/**
 * ooo-yay.com API
 * Resource-based API for ooo-yay.com.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FileDetails } from './FileDetails';
import {
    FileDetailsFromJSON,
    FileDetailsFromJSONTyped,
    FileDetailsToJSON,
} from './FileDetails';

/**
 * 
 * @export
 * @interface PagedFileDetails
 */
export interface PagedFileDetails {
    /**
     * 
     * @type {Array<FileDetails>}
     * @memberof PagedFileDetails
     */
    items: Array<FileDetails>;
    /**
     * 
     * @type {number}
     * @memberof PagedFileDetails
     */
    count: number;
}

/**
 * Check if a given object implements the PagedFileDetails interface.
 */
export function instanceOfPagedFileDetails(value: object): value is PagedFileDetails {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('count' in value) || value['count'] === undefined) return false;
    return true;
}

export function PagedFileDetailsFromJSON(json: any): PagedFileDetails {
    return PagedFileDetailsFromJSONTyped(json, false);
}

export function PagedFileDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): PagedFileDetails {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(FileDetailsFromJSON)),
        'count': json['count'],
    };
}

export function PagedFileDetailsToJSON(value?: PagedFileDetails | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'items': ((value['items'] as Array<any>).map(FileDetailsToJSON)),
        'count': value['count'],
    };
}

