/* tslint:disable */
/* eslint-disable */
/**
 * ooo-yay.com API
 * Resource-based API for ooo-yay.com.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostUpdate
 */
export interface PostUpdate {
    /**
     * 
     * @type {string}
     * @memberof PostUpdate
     */
    title?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PostUpdate
     */
    slug?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PostUpdate
     */
    content?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof PostUpdate
     */
    publishedAt?: Date | null;
    /**
     * 
     * @type {number}
     * @memberof PostUpdate
     */
    seriesId?: number | null;
}

/**
 * Check if a given object implements the PostUpdate interface.
 */
export function instanceOfPostUpdate(value: object): value is PostUpdate {
    return true;
}

export function PostUpdateFromJSON(json: any): PostUpdate {
    return PostUpdateFromJSONTyped(json, false);
}

export function PostUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'] == null ? undefined : json['title'],
        'slug': json['slug'] == null ? undefined : json['slug'],
        'content': json['content'] == null ? undefined : json['content'],
        'publishedAt': json['published_at'] == null ? undefined : (new Date(json['published_at'])),
        'seriesId': json['series_id'] == null ? undefined : json['series_id'],
    };
}

export function PostUpdateToJSON(value?: PostUpdate | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'title': value['title'],
        'slug': value['slug'],
        'content': value['content'],
        'published_at': value['publishedAt'] == null ? undefined : ((value['publishedAt'] as any).toISOString()),
        'series_id': value['seriesId'],
    };
}

