/* tslint:disable */
/* eslint-disable */
/**
 * ooo-yay.com API
 * Resource-based API for ooo-yay.com.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostSummaryForSeries
 */
export interface PostSummaryForSeries {
    /**
     * 
     * @type {number}
     * @memberof PostSummaryForSeries
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof PostSummaryForSeries
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof PostSummaryForSeries
     */
    slug: string;
    /**
     * 
     * @type {number}
     * @memberof PostSummaryForSeries
     */
    year?: number | null;
    /**
     * 
     * @type {Date}
     * @memberof PostSummaryForSeries
     */
    publishedAt?: Date | null;
}

/**
 * Check if a given object implements the PostSummaryForSeries interface.
 */
export function instanceOfPostSummaryForSeries(value: object): value is PostSummaryForSeries {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('slug' in value) || value['slug'] === undefined) return false;
    return true;
}

export function PostSummaryForSeriesFromJSON(json: any): PostSummaryForSeries {
    return PostSummaryForSeriesFromJSONTyped(json, false);
}

export function PostSummaryForSeriesFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostSummaryForSeries {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'title': json['title'],
        'slug': json['slug'],
        'year': json['year'] == null ? undefined : json['year'],
        'publishedAt': json['published_at'] == null ? undefined : (new Date(json['published_at'])),
    };
}

export function PostSummaryForSeriesToJSON(value?: PostSummaryForSeries | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'title': value['title'],
        'slug': value['slug'],
        'year': value['year'],
        'published_at': value['publishedAt'] == null ? undefined : ((value['publishedAt'] as any).toISOString()),
    };
}

