/* tslint:disable */
/* eslint-disable */
/**
 * ooo-yay.com API
 * Resource-based API for ooo-yay.com.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostSummary
 */
export interface PostSummary {
    /**
     * 
     * @type {number}
     * @memberof PostSummary
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof PostSummary
     */
    title: string;
    /**
     * 
     * @type {Date}
     * @memberof PostSummary
     */
    published?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof PostSummary
     */
    slug: string;
}

/**
 * Check if a given object implements the PostSummary interface.
 */
export function instanceOfPostSummary(value: object): value is PostSummary {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('slug' in value) || value['slug'] === undefined) return false;
    return true;
}

export function PostSummaryFromJSON(json: any): PostSummary {
    return PostSummaryFromJSONTyped(json, false);
}

export function PostSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostSummary {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'title': json['title'],
        'published': json['published'] == null ? undefined : (new Date(json['published'])),
        'slug': json['slug'],
    };
}

export function PostSummaryToJSON(value?: PostSummary | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'title': value['title'],
        'published': value['published'] == null ? undefined : ((value['published'] as any).toISOString()),
        'slug': value['slug'],
    };
}

