/* tslint:disable */
/* eslint-disable */
/**
 * ooo-yay.com API
 * Resource-based API for ooo-yay.com.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostMutate
 */
export interface PostMutate {
    /**
     * 
     * @type {string}
     * @memberof PostMutate
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof PostMutate
     */
    content: string;
    /**
     * 
     * @type {Date}
     * @memberof PostMutate
     */
    published?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof PostMutate
     */
    slug: string;
    /**
     * 
     * @type {number}
     * @memberof PostMutate
     */
    seriesId?: number | null;
}

/**
 * Check if a given object implements the PostMutate interface.
 */
export function instanceOfPostMutate(value: object): value is PostMutate {
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('content' in value) || value['content'] === undefined) return false;
    if (!('slug' in value) || value['slug'] === undefined) return false;
    return true;
}

export function PostMutateFromJSON(json: any): PostMutate {
    return PostMutateFromJSONTyped(json, false);
}

export function PostMutateFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostMutate {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'content': json['content'],
        'published': json['published'] == null ? undefined : (new Date(json['published'])),
        'slug': json['slug'],
        'seriesId': json['series_id'] == null ? undefined : json['series_id'],
    };
}

export function PostMutateToJSON(value?: PostMutate | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'title': value['title'],
        'content': value['content'],
        'published': value['published'] == null ? undefined : ((value['published'] as any).toISOString()),
        'slug': value['slug'],
        'series_id': value['seriesId'],
    };
}

