/* tslint:disable */
/* eslint-disable */
/**
 * ooo-yay.com API
 * Resource-based API for ooo-yay.com.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SeriesIdOrSlug1
 */
export interface SeriesIdOrSlug1 {
}

/**
 * Check if a given object implements the SeriesIdOrSlug1 interface.
 */
export function instanceOfSeriesIdOrSlug1(value: object): value is SeriesIdOrSlug1 {
    return true;
}

export function SeriesIdOrSlug1FromJSON(json: any): SeriesIdOrSlug1 {
    return SeriesIdOrSlug1FromJSONTyped(json, false);
}

export function SeriesIdOrSlug1FromJSONTyped(json: any, ignoreDiscriminator: boolean): SeriesIdOrSlug1 {
    return json;
}

export function SeriesIdOrSlug1ToJSON(value?: SeriesIdOrSlug1 | null): any {
    return value;
}

