/* tslint:disable */
/* eslint-disable */
/**
 * ooo-yay.com API
 * Resource-based API for ooo-yay.com.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SeriesIdOrSlug
 */
export interface SeriesIdOrSlug {
}

/**
 * Check if a given object implements the SeriesIdOrSlug interface.
 */
export function instanceOfSeriesIdOrSlug(value: object): value is SeriesIdOrSlug {
    return true;
}

export function SeriesIdOrSlugFromJSON(json: any): SeriesIdOrSlug {
    return SeriesIdOrSlugFromJSONTyped(json, false);
}

export function SeriesIdOrSlugFromJSONTyped(json: any, ignoreDiscriminator: boolean): SeriesIdOrSlug {
    return json;
}

export function SeriesIdOrSlugToJSON(value?: SeriesIdOrSlug | null): any {
    return value;
}

