/* tslint:disable */
/* eslint-disable */
/**
 * ooo-yay.com API
 * Resource-based API for ooo-yay.com.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SeriesSummary
 */
export interface SeriesSummary {
    /**
     * 
     * @type {number}
     * @memberof SeriesSummary
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof SeriesSummary
     */
    name: string;
}

/**
 * Check if a given object implements the SeriesSummary interface.
 */
export function instanceOfSeriesSummary(value: object): value is SeriesSummary {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function SeriesSummaryFromJSON(json: any): SeriesSummary {
    return SeriesSummaryFromJSONTyped(json, false);
}

export function SeriesSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): SeriesSummary {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
    };
}

export function SeriesSummaryToJSON(value?: SeriesSummary | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'name': value['name'],
    };
}

