/* tslint:disable */
/* eslint-disable */
/**
 * ooo-yay.com API
 * Resource-based API for ooo-yay.com.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SeriesCreate
 */
export interface SeriesCreate {
    /**
     * 
     * @type {string}
     * @memberof SeriesCreate
     */
    title: string;
    /**
     * URL-friendly identifier. Will be auto-generated from title if not provided.
     * @type {string}
     * @memberof SeriesCreate
     */
    slug: string;
    /**
     * 
     * @type {string}
     * @memberof SeriesCreate
     */
    description?: string | null;
}

/**
 * Check if a given object implements the SeriesCreate interface.
 */
export function instanceOfSeriesCreate(value: object): value is SeriesCreate {
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('slug' in value) || value['slug'] === undefined) return false;
    return true;
}

export function SeriesCreateFromJSON(json: any): SeriesCreate {
    return SeriesCreateFromJSONTyped(json, false);
}

export function SeriesCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): SeriesCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'slug': json['slug'],
        'description': json['description'] == null ? undefined : json['description'],
    };
}

export function SeriesCreateToJSON(value?: SeriesCreate | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'title': value['title'],
        'slug': value['slug'],
        'description': value['description'],
    };
}

