/* tslint:disable */
/* eslint-disable */
/**
 * ooo-yay.com API
 * Resource-based API for ooo-yay.com.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PostSummaryForSeries } from './PostSummaryForSeries';
import {
    PostSummaryForSeriesFromJSON,
    PostSummaryForSeriesFromJSONTyped,
    PostSummaryForSeriesToJSON,
} from './PostSummaryForSeries';

/**
 * 
 * @export
 * @interface SeriesDetailPublic
 */
export interface SeriesDetailPublic {
    /**
     * 
     * @type {string}
     * @memberof SeriesDetailPublic
     */
    title: string;
    /**
     * URL-friendly identifier. Will be auto-generated from title if not provided.
     * @type {string}
     * @memberof SeriesDetailPublic
     */
    slug: string;
    /**
     * 
     * @type {string}
     * @memberof SeriesDetailPublic
     */
    description?: string | null;
    /**
     * 
     * @type {number}
     * @memberof SeriesDetailPublic
     */
    id: number;
    /**
     * 
     * @type {Date}
     * @memberof SeriesDetailPublic
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof SeriesDetailPublic
     */
    updatedAt: Date;
    /**
     * 
     * @type {number}
     * @memberof SeriesDetailPublic
     */
    postCount?: number;
    /**
     * 
     * @type {Array<PostSummaryForSeries>}
     * @memberof SeriesDetailPublic
     */
    posts?: Array<PostSummaryForSeries>;
}

/**
 * Check if a given object implements the SeriesDetailPublic interface.
 */
export function instanceOfSeriesDetailPublic(value: object): value is SeriesDetailPublic {
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('slug' in value) || value['slug'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function SeriesDetailPublicFromJSON(json: any): SeriesDetailPublic {
    return SeriesDetailPublicFromJSONTyped(json, false);
}

export function SeriesDetailPublicFromJSONTyped(json: any, ignoreDiscriminator: boolean): SeriesDetailPublic {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'slug': json['slug'],
        'description': json['description'] == null ? undefined : json['description'],
        'id': json['id'],
        'createdAt': (new Date(json['created_at'])),
        'updatedAt': (new Date(json['updated_at'])),
        'postCount': json['post_count'] == null ? undefined : json['post_count'],
        'posts': json['posts'] == null ? undefined : ((json['posts'] as Array<any>).map(PostSummaryForSeriesFromJSON)),
    };
}

export function SeriesDetailPublicToJSON(value?: SeriesDetailPublic | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'title': value['title'],
        'slug': value['slug'],
        'description': value['description'],
        'id': value['id'],
        'created_at': ((value['createdAt']).toISOString()),
        'updated_at': ((value['updatedAt']).toISOString()),
        'post_count': value['postCount'],
        'posts': value['posts'] == null ? undefined : ((value['posts'] as Array<any>).map(PostSummaryForSeriesToJSON)),
    };
}

