/* tslint:disable */
/* eslint-disable */
/**
 * ooo-yay.com API
 * Resource-based API for ooo-yay.com.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ShareCodeCreate
 */
export interface ShareCodeCreate {
    /**
     * 
     * @type {string}
     * @memberof ShareCodeCreate
     */
    note?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof ShareCodeCreate
     */
    expiresAt?: Date | null;
}

/**
 * Check if a given object implements the ShareCodeCreate interface.
 */
export function instanceOfShareCodeCreate(value: object): value is ShareCodeCreate {
    return true;
}

export function ShareCodeCreateFromJSON(json: any): ShareCodeCreate {
    return ShareCodeCreateFromJSONTyped(json, false);
}

export function ShareCodeCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): ShareCodeCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'note': json['note'] == null ? undefined : json['note'],
        'expiresAt': json['expires_at'] == null ? undefined : (new Date(json['expires_at'])),
    };
}

export function ShareCodeCreateToJSON(value?: ShareCodeCreate | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'note': value['note'],
        'expires_at': value['expiresAt'] == null ? undefined : ((value['expiresAt'] as any).toISOString()),
    };
}

