/* tslint:disable */
/* eslint-disable */
/**
 * ooo-yay.com API
 * Resource-based API for ooo-yay.com.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TokenRefreshInputSchema
 */
export interface TokenRefreshInputSchema {
    /**
     * 
     * @type {string}
     * @memberof TokenRefreshInputSchema
     */
    refresh: string;
}

/**
 * Check if a given object implements the TokenRefreshInputSchema interface.
 */
export function instanceOfTokenRefreshInputSchema(value: object): value is TokenRefreshInputSchema {
    if (!('refresh' in value) || value['refresh'] === undefined) return false;
    return true;
}

export function TokenRefreshInputSchemaFromJSON(json: any): TokenRefreshInputSchema {
    return TokenRefreshInputSchemaFromJSONTyped(json, false);
}

export function TokenRefreshInputSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): TokenRefreshInputSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'refresh': json['refresh'],
    };
}

export function TokenRefreshInputSchemaToJSON(value?: TokenRefreshInputSchema | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'refresh': value['refresh'],
    };
}

