/* tslint:disable */
/* eslint-disable */
/**
 * ooo-yay.com API
 * Resource-based API for ooo-yay.com.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TokenObtainPairInputSchema
 */
export interface TokenObtainPairInputSchema {
    /**
     * 
     * @type {string}
     * @memberof TokenObtainPairInputSchema
     */
    password: string;
    /**
     * Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
     * @type {string}
     * @memberof TokenObtainPairInputSchema
     */
    username: string;
}

/**
 * Check if a given object implements the TokenObtainPairInputSchema interface.
 */
export function instanceOfTokenObtainPairInputSchema(value: object): value is TokenObtainPairInputSchema {
    if (!('password' in value) || value['password'] === undefined) return false;
    if (!('username' in value) || value['username'] === undefined) return false;
    return true;
}

export function TokenObtainPairInputSchemaFromJSON(json: any): TokenObtainPairInputSchema {
    return TokenObtainPairInputSchemaFromJSONTyped(json, false);
}

export function TokenObtainPairInputSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): TokenObtainPairInputSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'password': json['password'],
        'username': json['username'],
    };
}

export function TokenObtainPairInputSchemaToJSON(value?: TokenObtainPairInputSchema | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'password': value['password'],
        'username': value['username'],
    };
}

