/* tslint:disable */
/* eslint-disable */
/**
 * ooo-yay.com API
 * Resource-based API for ooo-yay.com.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateAccount
 */
export interface UpdateAccount {
    /**
     * 
     * @type {string}
     * @memberof UpdateAccount
     */
    username?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateAccount
     */
    email?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateAccount
     */
    oldPassword?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateAccount
     */
    newPassword?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateAccount
     */
    firstName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateAccount
     */
    lastName?: string | null;
}

/**
 * Check if a given object implements the UpdateAccount interface.
 */
export function instanceOfUpdateAccount(value: object): value is UpdateAccount {
    return true;
}

export function UpdateAccountFromJSON(json: any): UpdateAccount {
    return UpdateAccountFromJSONTyped(json, false);
}

export function UpdateAccountFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateAccount {
    if (json == null) {
        return json;
    }
    return {
        
        'username': json['username'] == null ? undefined : json['username'],
        'email': json['email'] == null ? undefined : json['email'],
        'oldPassword': json['old_password'] == null ? undefined : json['old_password'],
        'newPassword': json['new_password'] == null ? undefined : json['new_password'],
        'firstName': json['first_name'] == null ? undefined : json['first_name'],
        'lastName': json['last_name'] == null ? undefined : json['last_name'],
    };
}

export function UpdateAccountToJSON(value?: UpdateAccount | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'username': value['username'],
        'email': value['email'],
        'old_password': value['oldPassword'],
        'new_password': value['newPassword'],
        'first_name': value['firstName'],
        'last_name': value['lastName'],
    };
}

