services:
  postgres:
    image: postgres:16-bookworm
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: blog
    volumes:
      - ./dbdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  django:
    build: 
      context: ./api
      target: development

    container_name: django
    volumes:
      - ./api:/app
    environment:
      - ENV_FILE=.env.docker
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    restart: on-failure

  ui:
    build: 
      context: ./ui
      target: development
    container_name: ui
    command: npm run dev
    environment:
      - VITE_API_URL=http://localhost:8000
    volumes:
      - ./ui:/app
    ports:
      - "3000:3000"
    depends_on:
      - django