services:
  postgres:
    image: postgres:16-bookworm
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: blog
    volumes:
      - ./dbdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  django:
    build: 
      context: ./api
      target: development

    container_name: django
    volumes:
      - ./api:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  svelte:
    build: 
      context: ./ui
      target: development
    container_name: svelte
    command: npm run dev
    volumes:
      - ./ui:/app
    ports:
      - "5173:5173"
      - "24678:24678"
    depends_on:
      - django