/* tslint:disable */
/* eslint-disable */
/**
 * ooo-yay.com API
 * Resource-based API for ooo-yay.com.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ContentType,
  HealthResponse,
} from '../models/index';
import {
    ContentTypeFromJSON,
    ContentTypeToJSON,
    HealthResponseFromJSON,
    HealthResponseToJSON,
} from '../models/index';

/**
 * 
 */
export class DefaultApi extends runtime.BaseAPI {

    /**
     * Returns a simple health check response.
     * Health check
     */
    async apiHealthcheckRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<HealthResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/health`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => HealthResponseFromJSON(jsonValue));
    }

    /**
     * Returns a simple health check response.
     * Health check
     */
    async apiHealthcheck(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<HealthResponse> {
        const response = await this.apiHealthcheckRaw(initOverrides);
        return await response.value();
    }

    /**
     * List all available content types in the system. Content types represent the models available in the Django application. This endpoint is restricted to staff users only as it\'s primarily used for administrative purposes.
     * List content types
     */
    async contenttypesListContentTypesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ContentType>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JWTAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/contenttypes/`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ContentTypeFromJSON));
    }

    /**
     * List all available content types in the system. Content types represent the models available in the Django application. This endpoint is restricted to staff users only as it\'s primarily used for administrative purposes.
     * List content types
     */
    async contenttypesListContentTypes(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ContentType>> {
        const response = await this.contenttypesListContentTypesRaw(initOverrides);
        return await response.value();
    }

}
