# Generated by Django 5.1.9 on 2025-06-11 06:13

from django.db import migrations, models

import resume.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("company", models.CharField(max_length=200)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("is_current", models.BooleanField(default=False)),
                ("achievements", models.TextField()),
            ],
            options={
                "verbose_name_plural": "Experience",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="Proficiency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("category", models.CharField(max_length=100)),
                ("items", models.JSONField()),
            ],
            options={
                "verbose_name_plural": "Proficiencies",
            },
        ),
        migrations.CreateModel(
            name="Resume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("github_url", models.URLField(validators=[resume.models.validate_url])),
                ("website_url", models.URLField(validators=[resume.models.validate_url])),
                ("bio", models.TextField()),
                ("experiences", models.ManyToManyField(to="resume.experience")),
                ("proficiencies", models.ManyToManyField(to="resume.proficiency")),
            ],
        ),
    ]
