# Generated by Django 5.1 on 2024-09-08 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar_link",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
