# Generated by Django 5.1.1 on 2025-05-14 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='website_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
