/* tslint:disable */
/* eslint-disable */
/**
 * ooo-yay.com API
 * Resource-based API for ooo-yay.com.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AdminUserDetails,
  AdminUserModify,
  AuthError,
  NewAccount,
  PagedAdminUserDetails,
  UpdateAccount,
  UserSelf,
} from '../models/index';
import {
    AdminUserDetailsFromJSON,
    AdminUserDetailsToJSON,
    AdminUserModifyFromJSON,
    AdminUserModifyToJSON,
    AuthErrorFromJSON,
    AuthErrorToJSON,
    NewAccountFromJSON,
    NewAccountToJSON,
    PagedAdminUserDetailsFromJSON,
    PagedAdminUserDetailsToJSON,
    UpdateAccountFromJSON,
    UpdateAccountToJSON,
    UserSelfFromJSON,
    UserSelfToJSON,
} from '../models/index';

export interface ApiDeleteUserRequest {
    userId: number;
}

export interface ApiGetUserRequest {
    userId: number;
}

export interface ApiListUsersRequest {
    limit?: number;
    offset?: number;
}

export interface ApiSignUpRequest {
    newAccount: NewAccount;
}

export interface ApiUpdateSelfRequest {
    updateAccount: UpdateAccount;
}

export interface ApiUpdateUserRequest {
    userId: number;
    adminUserModify: AdminUserModify;
}

/**
 * 
 */
export class AccountsApi extends runtime.BaseAPI {

    /**
     * Deletes the calling user
     * Delete Self
     */
    async apiDeleteSelfRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JWTAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/accounts/me`,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Deletes the calling user
     * Delete Self
     */
    async apiDeleteSelf(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiDeleteSelfRaw(initOverrides);
    }

    /**
     * Deletes a user
     * Delete User
     */
    async apiDeleteUserRaw(requestParameters: ApiDeleteUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling apiDeleteUser().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JWTAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/accounts/{user_id}`.replace(`{${"user_id"}}`, encodeURIComponent(String(requestParameters['userId']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Deletes a user
     * Delete User
     */
    async apiDeleteUser(requestParameters: ApiDeleteUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiDeleteUserRaw(requestParameters, initOverrides);
    }

    /**
     * Returns a specific user
     * Get User
     */
    async apiGetUserRaw(requestParameters: ApiGetUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AdminUserDetails>> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling apiGetUser().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JWTAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/accounts/{user_id}`.replace(`{${"user_id"}}`, encodeURIComponent(String(requestParameters['userId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AdminUserDetailsFromJSON(jsonValue));
    }

    /**
     * Returns a specific user
     * Get User
     */
    async apiGetUser(requestParameters: ApiGetUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AdminUserDetails> {
        const response = await this.apiGetUserRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns a list of all users
     * List Users
     */
    async apiListUsersRaw(requestParameters: ApiListUsersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PagedAdminUserDetails>> {
        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JWTAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/accounts/`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PagedAdminUserDetailsFromJSON(jsonValue));
    }

    /**
     * Returns a list of all users
     * List Users
     */
    async apiListUsers(requestParameters: ApiListUsersRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PagedAdminUserDetails> {
        const response = await this.apiListUsersRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates a new user
     * Sign Up
     */
    async apiSignUpRaw(requestParameters: ApiSignUpRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserSelf>> {
        if (requestParameters['newAccount'] == null) {
            throw new runtime.RequiredError(
                'newAccount',
                'Required parameter "newAccount" was null or undefined when calling apiSignUp().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JWTAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/accounts/sign_up`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: NewAccountToJSON(requestParameters['newAccount']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserSelfFromJSON(jsonValue));
    }

    /**
     * Creates a new user
     * Sign Up
     */
    async apiSignUp(requestParameters: ApiSignUpRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserSelf> {
        const response = await this.apiSignUpRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Updates the calling users details
     * Update Self
     */
    async apiUpdateSelfRaw(requestParameters: ApiUpdateSelfRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserSelf>> {
        if (requestParameters['updateAccount'] == null) {
            throw new runtime.RequiredError(
                'updateAccount',
                'Required parameter "updateAccount" was null or undefined when calling apiUpdateSelf().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JWTAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/accounts/me`,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateAccountToJSON(requestParameters['updateAccount']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserSelfFromJSON(jsonValue));
    }

    /**
     * Updates the calling users details
     * Update Self
     */
    async apiUpdateSelf(requestParameters: ApiUpdateSelfRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserSelf> {
        const response = await this.apiUpdateSelfRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Updates a user
     * Update User
     */
    async apiUpdateUserRaw(requestParameters: ApiUpdateUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AdminUserDetails>> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling apiUpdateUser().'
            );
        }

        if (requestParameters['adminUserModify'] == null) {
            throw new runtime.RequiredError(
                'adminUserModify',
                'Required parameter "adminUserModify" was null or undefined when calling apiUpdateUser().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JWTAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/accounts/{user_id}`.replace(`{${"user_id"}}`, encodeURIComponent(String(requestParameters['userId']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: AdminUserModifyToJSON(requestParameters['adminUserModify']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AdminUserDetailsFromJSON(jsonValue));
    }

    /**
     * Updates a user
     * Update User
     */
    async apiUpdateUser(requestParameters: ApiUpdateUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AdminUserDetails> {
        const response = await this.apiUpdateUserRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns the calling users details
     * Whoami
     */
    async apiWhoamiRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserSelf>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JWTAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/accounts/me`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserSelfFromJSON(jsonValue));
    }

    /**
     * Returns the calling users details
     * Whoami
     */
    async apiWhoami(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserSelf> {
        const response = await this.apiWhoamiRaw(initOverrides);
        return await response.value();
    }

}
