/* tslint:disable */
/* eslint-disable */
/**
 * ooo-yay.com API
 * Resource-based API for ooo-yay.com.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CommentCreate,
  CommentList,
  CommentMutate,
  PagedCommentList,
} from '../models/index';
import {
    CommentCreateFromJSON,
    CommentCreateToJSON,
    CommentListFromJSON,
    CommentListToJSON,
    CommentMutateFromJSON,
    CommentMutateToJSON,
    PagedCommentListFromJSON,
    PagedCommentListToJSON,
} from '../models/index';

export interface BlogApiCreateCommentRequest {
    commentCreate: CommentCreate;
}

export interface BlogApiDeleteCommentRequest {
    id: number;
}

export interface BlogApiGetCommentRequest {
    id: number;
}

export interface BlogApiListCommentsRequest {
    postId?: number | null;
    topLevel?: boolean;
    limit?: number;
    offset?: number;
}

export interface BlogApiUpdateCommentRequest {
    id: number;
    commentMutate: CommentMutate;
}

/**
 * 
 */
export class CommentsApi extends runtime.BaseAPI {

    /**
     * Creates a comment
     * Create Comment
     */
    async blogApiCreateCommentRaw(requestParameters: BlogApiCreateCommentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CommentList>> {
        if (requestParameters['commentCreate'] == null) {
            throw new runtime.RequiredError(
                'commentCreate',
                'Required parameter "commentCreate" was null or undefined when calling blogApiCreateComment().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JWTAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/comments/`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CommentCreateToJSON(requestParameters['commentCreate']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CommentListFromJSON(jsonValue));
    }

    /**
     * Creates a comment
     * Create Comment
     */
    async blogApiCreateComment(requestParameters: BlogApiCreateCommentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CommentList> {
        const response = await this.blogApiCreateCommentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete Comment
     */
    async blogApiDeleteCommentRaw(requestParameters: BlogApiDeleteCommentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling blogApiDeleteComment().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JWTAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/comments/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete Comment
     */
    async blogApiDeleteComment(requestParameters: BlogApiDeleteCommentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.blogApiDeleteCommentRaw(requestParameters, initOverrides);
    }

    /**
     * Gets all the details of a comment.
     * Get Comment
     */
    async blogApiGetCommentRaw(requestParameters: BlogApiGetCommentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CommentList>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling blogApiGetComment().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JWTAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/comments/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CommentListFromJSON(jsonValue));
    }

    /**
     * Gets all the details of a comment.
     * Get Comment
     */
    async blogApiGetComment(requestParameters: BlogApiGetCommentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CommentList> {
        const response = await this.blogApiGetCommentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List all comments for a post
     * List Comments
     */
    async blogApiListCommentsRaw(requestParameters: BlogApiListCommentsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PagedCommentList>> {
        const queryParameters: any = {};

        if (requestParameters['postId'] != null) {
            queryParameters['post_id'] = requestParameters['postId'];
        }

        if (requestParameters['topLevel'] != null) {
            queryParameters['top_level'] = requestParameters['topLevel'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JWTAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/comments/`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PagedCommentListFromJSON(jsonValue));
    }

    /**
     * List all comments for a post
     * List Comments
     */
    async blogApiListComments(requestParameters: BlogApiListCommentsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PagedCommentList> {
        const response = await this.blogApiListCommentsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update Comment
     */
    async blogApiUpdateCommentRaw(requestParameters: BlogApiUpdateCommentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CommentList>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling blogApiUpdateComment().'
            );
        }

        if (requestParameters['commentMutate'] == null) {
            throw new runtime.RequiredError(
                'commentMutate',
                'Required parameter "commentMutate" was null or undefined when calling blogApiUpdateComment().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JWTAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/comments/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: CommentMutateToJSON(requestParameters['commentMutate']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CommentListFromJSON(jsonValue));
    }

    /**
     * Update Comment
     */
    async blogApiUpdateComment(requestParameters: BlogApiUpdateCommentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CommentList> {
        const response = await this.blogApiUpdateCommentRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
