/* tslint:disable */
/* eslint-disable */
/**
 * ooo-yay.com API
 * Resource-based API for ooo-yay.com.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  FileDetails,
  FileMetadata,
  FileMutateMetadata,
  PagedFileDetails,
} from '../models/index';
import {
    FileDetailsFromJSON,
    FileDetailsToJSON,
    FileMetadataFromJSON,
    FileMetadataToJSON,
    FileMutateMetadataFromJSON,
    FileMutateMetadataToJSON,
    PagedFileDetailsFromJSON,
    PagedFileDetailsToJSON,
} from '../models/index';

export interface ApiCreateFileRequest {
    upload: Blob;
    metadata: FileMetadata;
}

export interface ApiDeleteFileRequest {
    id: number;
}

export interface ApiGetFileRequest {
    id: number;
}

export interface ApiListFilesRequest {
    visibility?: ApiListFilesVisibilityEnum;
    limit?: number;
    offset?: number;
}

export interface ApiUpdateFileRequest {
    id: number;
    fileMutateMetadata: FileMutateMetadata;
}

/**
 * 
 */
export class FilesApi extends runtime.BaseAPI {

    /**
     * Creates a file with or without post associations.
     * Create File
     */
    async apiCreateFileRaw(requestParameters: ApiCreateFileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FileDetails>> {
        if (requestParameters['upload'] == null) {
            throw new runtime.RequiredError(
                'upload',
                'Required parameter "upload" was null or undefined when calling apiCreateFile().'
            );
        }

        if (requestParameters['metadata'] == null) {
            throw new runtime.RequiredError(
                'metadata',
                'Required parameter "metadata" was null or undefined when calling apiCreateFile().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JWTAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['upload'] != null) {
            formParams.append('upload', requestParameters['upload'] as any);
        }

        if (requestParameters['metadata'] != null) {
            formParams.append('metadata', new Blob([JSON.stringify(FileMetadataToJSON(requestParameters['metadata']))], { type: "application/json", }));
                    }

        const response = await this.request({
            path: `/api/files/`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FileDetailsFromJSON(jsonValue));
    }

    /**
     * Creates a file with or without post associations.
     * Create File
     */
    async apiCreateFile(requestParameters: ApiCreateFileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FileDetails> {
        const response = await this.apiCreateFileRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Deletes a file from the database and S3.
     * Delete File
     */
    async apiDeleteFileRaw(requestParameters: ApiDeleteFileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiDeleteFile().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JWTAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/files/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Deletes a file from the database and S3.
     * Delete File
     */
    async apiDeleteFile(requestParameters: ApiDeleteFileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiDeleteFileRaw(requestParameters, initOverrides);
    }

    /**
     * Gets all the details of a file.
     * Get File
     */
    async apiGetFileRaw(requestParameters: ApiGetFileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FileDetails>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiGetFile().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JWTAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/files/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FileDetailsFromJSON(jsonValue));
    }

    /**
     * Gets all the details of a file.
     * Get File
     */
    async apiGetFile(requestParameters: ApiGetFileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FileDetails> {
        const response = await this.apiGetFileRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List all files
     * List Files
     */
    async apiListFilesRaw(requestParameters: ApiListFilesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PagedFileDetails>> {
        const queryParameters: any = {};

        if (requestParameters['visibility'] != null) {
            queryParameters['visibility'] = requestParameters['visibility'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JWTAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/files/`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PagedFileDetailsFromJSON(jsonValue));
    }

    /**
     * List all files
     * List Files
     */
    async apiListFiles(requestParameters: ApiListFilesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PagedFileDetails> {
        const response = await this.apiListFilesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Updates a file, namely the posts associated with the file. File properties are immutable.
     * Update File
     */
    async apiUpdateFileRaw(requestParameters: ApiUpdateFileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FileDetails>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiUpdateFile().'
            );
        }

        if (requestParameters['fileMutateMetadata'] == null) {
            throw new runtime.RequiredError(
                'fileMutateMetadata',
                'Required parameter "fileMutateMetadata" was null or undefined when calling apiUpdateFile().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JWTAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/files/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: FileMutateMetadataToJSON(requestParameters['fileMutateMetadata']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FileDetailsFromJSON(jsonValue));
    }

    /**
     * Updates a file, namely the posts associated with the file. File properties are immutable.
     * Update File
     */
    async apiUpdateFile(requestParameters: ApiUpdateFileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FileDetails> {
        const response = await this.apiUpdateFileRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const ApiListFilesVisibilityEnum = {
    Public: 'public',
    Private: 'private',
    All: 'all'
} as const;
export type ApiListFilesVisibilityEnum = typeof ApiListFilesVisibilityEnum[keyof typeof ApiListFilesVisibilityEnum];
