/* tslint:disable */
/* eslint-disable */
/**
 * ooo-yay.com API
 * Resource-based API for ooo-yay.com.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  FileDetails,
  PagedPostDetails,
  PostDetails,
  PostMutate,
  ValidationErrorResponse,
} from '../models/index';
import {
    FileDetailsFromJSON,
    FileDetailsToJSON,
    PagedPostDetailsFromJSON,
    PagedPostDetailsToJSON,
    PostDetailsFromJSON,
    PostDetailsToJSON,
    PostMutateFromJSON,
    PostMutateToJSON,
    ValidationErrorResponseFromJSON,
    ValidationErrorResponseToJSON,
} from '../models/index';

export interface ApiCreatePostRequest {
    postMutate: PostMutate;
}

export interface ApiDeletePostRequest {
    id: number;
}

export interface ApiGetPostByIdRequest {
    id: number;
}

export interface ApiGetPostBySlugRequest {
    slug: string;
    year?: number;
    draft?: boolean;
}

export interface ApiGetPostFilesByIdRequest {
    id: number;
}

export interface ApiListPostsRequest {
    all?: boolean;
    drafts?: boolean;
    limit?: number;
    offset?: number;
}

export interface ApiUpdatePostRequest {
    id: number;
    postMutate: PostMutate;
}

/**
 * 
 */
export class PostsApi extends runtime.BaseAPI {

    /**
     * Create Post
     */
    async apiCreatePostRaw(requestParameters: ApiCreatePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PostDetails>> {
        if (requestParameters['postMutate'] == null) {
            throw new runtime.RequiredError(
                'postMutate',
                'Required parameter "postMutate" was null or undefined when calling apiCreatePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JWTAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/posts/`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PostMutateToJSON(requestParameters['postMutate']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PostDetailsFromJSON(jsonValue));
    }

    /**
     * Create Post
     */
    async apiCreatePost(requestParameters: ApiCreatePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PostDetails> {
        const response = await this.apiCreatePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete Post
     */
    async apiDeletePostRaw(requestParameters: ApiDeletePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiDeletePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JWTAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/posts/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete Post
     */
    async apiDeletePost(requestParameters: ApiDeletePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiDeletePostRaw(requestParameters, initOverrides);
    }

    /**
     * Get Post By Id
     */
    async apiGetPostByIdRaw(requestParameters: ApiGetPostByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PostDetails>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiGetPostById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JWTAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/posts/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PostDetailsFromJSON(jsonValue));
    }

    /**
     * Get Post By Id
     */
    async apiGetPostById(requestParameters: ApiGetPostByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PostDetails> {
        const response = await this.apiGetPostByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get Post By Slug
     */
    async apiGetPostBySlugRaw(requestParameters: ApiGetPostBySlugRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PostDetails>> {
        if (requestParameters['slug'] == null) {
            throw new runtime.RequiredError(
                'slug',
                'Required parameter "slug" was null or undefined when calling apiGetPostBySlug().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['year'] != null) {
            queryParameters['year'] = requestParameters['year'];
        }

        if (requestParameters['draft'] != null) {
            queryParameters['draft'] = requestParameters['draft'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JWTAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/posts/slug/{slug}`.replace(`{${"slug"}}`, encodeURIComponent(String(requestParameters['slug']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PostDetailsFromJSON(jsonValue));
    }

    /**
     * Get Post By Slug
     */
    async apiGetPostBySlug(requestParameters: ApiGetPostBySlugRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PostDetails> {
        const response = await this.apiGetPostBySlugRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get Post Files By Id
     */
    async apiGetPostFilesByIdRaw(requestParameters: ApiGetPostFilesByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<FileDetails>>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiGetPostFilesById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JWTAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/posts/{id}/files`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(FileDetailsFromJSON));
    }

    /**
     * Get Post Files By Id
     */
    async apiGetPostFilesById(requestParameters: ApiGetPostFilesByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<FileDetails>> {
        const response = await this.apiGetPostFilesByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List Posts
     */
    async apiListPostsRaw(requestParameters: ApiListPostsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PagedPostDetails>> {
        const queryParameters: any = {};

        if (requestParameters['all'] != null) {
            queryParameters['all'] = requestParameters['all'];
        }

        if (requestParameters['drafts'] != null) {
            queryParameters['drafts'] = requestParameters['drafts'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JWTAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/posts/`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PagedPostDetailsFromJSON(jsonValue));
    }

    /**
     * List Posts
     */
    async apiListPosts(requestParameters: ApiListPostsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PagedPostDetails> {
        const response = await this.apiListPostsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update Post
     */
    async apiUpdatePostRaw(requestParameters: ApiUpdatePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PostDetails>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiUpdatePost().'
            );
        }

        if (requestParameters['postMutate'] == null) {
            throw new runtime.RequiredError(
                'postMutate',
                'Required parameter "postMutate" was null or undefined when calling apiUpdatePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JWTAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/posts/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: PostMutateToJSON(requestParameters['postMutate']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PostDetailsFromJSON(jsonValue));
    }

    /**
     * Update Post
     */
    async apiUpdatePost(requestParameters: ApiUpdatePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PostDetails> {
        const response = await this.apiUpdatePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
