/* tslint:disable */
/* eslint-disable */
/**
 * ooo-yay.com API
 * Resource-based API for ooo-yay.com.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  TokenObtainPairInputSchema,
  TokenObtainPairOutputSchema,
  TokenRefreshInputSchema,
  TokenRefreshOutputSchema,
  TokenVerifyInputSchema,
} from '../models/index';
import {
    TokenObtainPairInputSchemaFromJSON,
    TokenObtainPairInputSchemaToJSON,
    TokenObtainPairOutputSchemaFromJSON,
    TokenObtainPairOutputSchemaToJSON,
    TokenRefreshInputSchemaFromJSON,
    TokenRefreshInputSchemaToJSON,
    TokenRefreshOutputSchemaFromJSON,
    TokenRefreshOutputSchemaToJSON,
    TokenVerifyInputSchemaFromJSON,
    TokenVerifyInputSchemaToJSON,
} from '../models/index';

export interface ObtainPairRequest {
    tokenObtainPairInputSchema: TokenObtainPairInputSchema;
}

export interface RefreshRequest {
    tokenRefreshInputSchema: TokenRefreshInputSchema;
}

export interface VerifyRequest {
    tokenVerifyInputSchema: TokenVerifyInputSchema;
}

/**
 * 
 */
export class TokenApi extends runtime.BaseAPI {

    /**
     * Obtain Token
     */
    async obtainPairRaw(requestParameters: ObtainPairRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TokenObtainPairOutputSchema>> {
        if (requestParameters['tokenObtainPairInputSchema'] == null) {
            throw new runtime.RequiredError(
                'tokenObtainPairInputSchema',
                'Required parameter "tokenObtainPairInputSchema" was null or undefined when calling obtainPair().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/token/pair`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TokenObtainPairInputSchemaToJSON(requestParameters['tokenObtainPairInputSchema']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TokenObtainPairOutputSchemaFromJSON(jsonValue));
    }

    /**
     * Obtain Token
     */
    async obtainPair(requestParameters: ObtainPairRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TokenObtainPairOutputSchema> {
        const response = await this.obtainPairRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Refresh Token
     */
    async refreshRaw(requestParameters: RefreshRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TokenRefreshOutputSchema>> {
        if (requestParameters['tokenRefreshInputSchema'] == null) {
            throw new runtime.RequiredError(
                'tokenRefreshInputSchema',
                'Required parameter "tokenRefreshInputSchema" was null or undefined when calling refresh().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/token/refresh`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TokenRefreshInputSchemaToJSON(requestParameters['tokenRefreshInputSchema']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TokenRefreshOutputSchemaFromJSON(jsonValue));
    }

    /**
     * Refresh Token
     */
    async refresh(requestParameters: RefreshRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TokenRefreshOutputSchema> {
        const response = await this.refreshRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Verify Token
     */
    async verifyRaw(requestParameters: VerifyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        if (requestParameters['tokenVerifyInputSchema'] == null) {
            throw new runtime.RequiredError(
                'tokenVerifyInputSchema',
                'Required parameter "tokenVerifyInputSchema" was null or undefined when calling verify().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/token/verify`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TokenVerifyInputSchemaToJSON(requestParameters['tokenVerifyInputSchema']),
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Verify Token
     */
    async verify(requestParameters: VerifyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.verifyRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
