/* tslint:disable */
/* eslint-disable */
/**
 * ooo-yay.com API
 * Resource-based API for ooo-yay.com.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CommentCreate
 */
export interface CommentCreate {
    /**
     * 
     * @type {string}
     * @memberof CommentCreate
     */
    content: string;
    /**
     * 
     * @type {number}
     * @memberof CommentCreate
     */
    parentId?: number | null;
    /**
     * 
     * @type {number}
     * @memberof CommentCreate
     */
    postId: number;
}

/**
 * Check if a given object implements the CommentCreate interface.
 */
export function instanceOfCommentCreate(value: object): value is CommentCreate {
    if (!('content' in value) || value['content'] === undefined) return false;
    if (!('postId' in value) || value['postId'] === undefined) return false;
    return true;
}

export function CommentCreateFromJSON(json: any): CommentCreate {
    return CommentCreateFromJSONTyped(json, false);
}

export function CommentCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommentCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'content': json['content'],
        'parentId': json['parent_id'] == null ? undefined : json['parent_id'],
        'postId': json['post_id'],
    };
}

export function CommentCreateToJSON(value?: CommentCreate | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'content': value['content'],
        'parent_id': value['parentId'],
        'post_id': value['postId'],
    };
}

