/* tslint:disable */
/* eslint-disable */
/**
 * ooo-yay.com API
 * Resource-based API for ooo-yay.com.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ContentType
 */
export interface ContentType {
    /**
     * 
     * @type {number}
     * @memberof ContentType
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof ContentType
     */
    appLabel: string;
    /**
     * 
     * @type {string}
     * @memberof ContentType
     */
    model: string;
    /**
     * 
     * @type {string}
     * @memberof ContentType
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ContentType
     */
    appLabeledName: string;
}

/**
 * Check if a given object implements the ContentType interface.
 */
export function instanceOfContentType(value: object): value is ContentType {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('appLabel' in value) || value['appLabel'] === undefined) return false;
    if (!('model' in value) || value['model'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('appLabeledName' in value) || value['appLabeledName'] === undefined) return false;
    return true;
}

export function ContentTypeFromJSON(json: any): ContentType {
    return ContentTypeFromJSONTyped(json, false);
}

export function ContentTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContentType {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'appLabel': json['app_label'],
        'model': json['model'],
        'name': json['name'],
        'appLabeledName': json['app_labeled_name'],
    };
}

export function ContentTypeToJSON(value?: ContentType | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'app_label': value['appLabel'],
        'model': value['model'],
        'name': value['name'],
        'app_labeled_name': value['appLabeledName'],
    };
}

