/* tslint:disable */
/* eslint-disable */
/**
 * ooo-yay.com API
 * Resource-based API for ooo-yay.com.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FileMetadata
 */
export interface FileMetadata {
    /**
     * 
     * @type {Array<number>}
     * @memberof FileMetadata
     */
    posts?: Array<number> | null;
    /**
     * 
     * @type {string}
     * @memberof FileMetadata
     */
    visibility?: string;
}

/**
 * Check if a given object implements the FileMetadata interface.
 */
export function instanceOfFileMetadata(value: object): value is FileMetadata {
    return true;
}

export function FileMetadataFromJSON(json: any): FileMetadata {
    return FileMetadataFromJSONTyped(json, false);
}

export function FileMetadataFromJSONTyped(json: any, ignoreDiscriminator: boolean): FileMetadata {
    if (json == null) {
        return json;
    }
    return {
        
        'posts': json['posts'] == null ? undefined : json['posts'],
        'visibility': json['visibility'] == null ? undefined : json['visibility'],
    };
}

export function FileMetadataToJSON(value?: FileMetadata | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'posts': value['posts'],
        'visibility': value['visibility'],
    };
}

