/* tslint:disable */
/* eslint-disable */
/**
 * ooo-yay.com API
 * Resource-based API for ooo-yay.com.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserDetails } from './UserDetails';
import {
    UserDetailsFromJSON,
    UserDetailsFromJSONTyped,
    UserDetailsToJSON,
} from './UserDetails';

/**
 * 
 * @export
 * @interface PagedUserDetails
 */
export interface PagedUserDetails {
    /**
     * 
     * @type {Array<UserDetails>}
     * @memberof PagedUserDetails
     */
    items: Array<UserDetails>;
    /**
     * 
     * @type {number}
     * @memberof PagedUserDetails
     */
    count: number;
}

/**
 * Check if a given object implements the PagedUserDetails interface.
 */
export function instanceOfPagedUserDetails(value: object): value is PagedUserDetails {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('count' in value) || value['count'] === undefined) return false;
    return true;
}

export function PagedUserDetailsFromJSON(json: any): PagedUserDetails {
    return PagedUserDetailsFromJSONTyped(json, false);
}

export function PagedUserDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): PagedUserDetails {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(UserDetailsFromJSON)),
        'count': json['count'],
    };
}

export function PagedUserDetailsToJSON(value?: PagedUserDetails | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'items': ((value['items'] as Array<any>).map(UserDetailsToJSON)),
        'count': value['count'],
    };
}

