/* tslint:disable */
/* eslint-disable */
/**
 * ooo-yay.com API
 * Resource-based API for ooo-yay.com.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TokenVerifyInputSchema
 */
export interface TokenVerifyInputSchema {
    /**
     * 
     * @type {string}
     * @memberof TokenVerifyInputSchema
     */
    token: string;
}

/**
 * Check if a given object implements the TokenVerifyInputSchema interface.
 */
export function instanceOfTokenVerifyInputSchema(value: object): value is TokenVerifyInputSchema {
    if (!('token' in value) || value['token'] === undefined) return false;
    return true;
}

export function TokenVerifyInputSchemaFromJSON(json: any): TokenVerifyInputSchema {
    return TokenVerifyInputSchemaFromJSONTyped(json, false);
}

export function TokenVerifyInputSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): TokenVerifyInputSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'token': json['token'],
    };
}

export function TokenVerifyInputSchemaToJSON(value?: TokenVerifyInputSchema | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'token': value['token'],
    };
}

