/* tslint:disable */
/* eslint-disable */
/**
 * ooo-yay.com API
 * Resource-based API for ooo-yay.com.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TokenObtainPairOutputSchema
 */
export interface TokenObtainPairOutputSchema {
    /**
     * Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
     * @type {string}
     * @memberof TokenObtainPairOutputSchema
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof TokenObtainPairOutputSchema
     */
    refresh: string;
    /**
     * 
     * @type {string}
     * @memberof TokenObtainPairOutputSchema
     */
    access: string;
}

/**
 * Check if a given object implements the TokenObtainPairOutputSchema interface.
 */
export function instanceOfTokenObtainPairOutputSchema(value: object): value is TokenObtainPairOutputSchema {
    if (!('username' in value) || value['username'] === undefined) return false;
    if (!('refresh' in value) || value['refresh'] === undefined) return false;
    if (!('access' in value) || value['access'] === undefined) return false;
    return true;
}

export function TokenObtainPairOutputSchemaFromJSON(json: any): TokenObtainPairOutputSchema {
    return TokenObtainPairOutputSchemaFromJSONTyped(json, false);
}

export function TokenObtainPairOutputSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): TokenObtainPairOutputSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'username': json['username'],
        'refresh': json['refresh'],
        'access': json['access'],
    };
}

export function TokenObtainPairOutputSchemaToJSON(value?: TokenObtainPairOutputSchema | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'username': value['username'],
        'refresh': value['refresh'],
        'access': value['access'],
    };
}

