/* tslint:disable */
/* eslint-disable */
/**
 * ooo-yay.com API
 * Resource-based API for ooo-yay.com.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthError
 */
export interface AuthError {
    /**
     * 
     * @type {string}
     * @memberof AuthError
     */
    details: string;
}

/**
 * Check if a given object implements the AuthError interface.
 */
export function instanceOfAuthError(value: object): value is AuthError {
    if (!('details' in value) || value['details'] === undefined) return false;
    return true;
}

export function AuthErrorFromJSON(json: any): AuthError {
    return AuthErrorFromJSONTyped(json, false);
}

export function AuthErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthError {
    if (json == null) {
        return json;
    }
    return {
        
        'details': json['details'],
    };
}

export function AuthErrorToJSON(value?: AuthError | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'details': value['details'],
    };
}

