/* tslint:disable */
/* eslint-disable */
/**
 * ooo-yay.com API
 * Resource-based API for ooo-yay.com.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PostDetails } from './PostDetails';
import {
    PostDetailsFromJSON,
    PostDetailsFromJSONTyped,
    PostDetailsToJSON,
} from './PostDetails';
import type { AuthorSummary } from './AuthorSummary';
import {
    AuthorSummaryFromJSON,
    AuthorSummaryFromJSONTyped,
    AuthorSummaryToJSON,
} from './AuthorSummary';

/**
 * 
 * @export
 * @interface CommentList
 */
export interface CommentList {
    /**
     * 
     * @type {number}
     * @memberof CommentList
     */
    id: number;
    /**
     * 
     * @type {AuthorSummary}
     * @memberof CommentList
     */
    author: AuthorSummary;
    /**
     * 
     * @type {string}
     * @memberof CommentList
     */
    content: string;
    /**
     * 
     * @type {Array<CommentList>}
     * @memberof CommentList
     */
    children: Array<CommentList>;
    /**
     * 
     * @type {Date}
     * @memberof CommentList
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof CommentList
     */
    updatedAt: Date;
    /**
     * 
     * @type {PostDetails}
     * @memberof CommentList
     */
    post: PostDetails;
}

/**
 * Check if a given object implements the CommentList interface.
 */
export function instanceOfCommentList(value: object): value is CommentList {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('author' in value) || value['author'] === undefined) return false;
    if (!('content' in value) || value['content'] === undefined) return false;
    if (!('children' in value) || value['children'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('post' in value) || value['post'] === undefined) return false;
    return true;
}

export function CommentListFromJSON(json: any): CommentList {
    return CommentListFromJSONTyped(json, false);
}

export function CommentListFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommentList {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'author': AuthorSummaryFromJSON(json['author']),
        'content': json['content'],
        'children': ((json['children'] as Array<any>).map(CommentListFromJSON)),
        'createdAt': (new Date(json['created_at'])),
        'updatedAt': (new Date(json['updated_at'])),
        'post': PostDetailsFromJSON(json['post']),
    };
}

export function CommentListToJSON(value?: CommentList | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'author': AuthorSummaryToJSON(value['author']),
        'content': value['content'],
        'children': ((value['children'] as Array<any>).map(CommentListToJSON)),
        'created_at': ((value['createdAt']).toISOString()),
        'updated_at': ((value['updatedAt']).toISOString()),
        'post': PostDetailsToJSON(value['post']),
    };
}

