/* tslint:disable */
/* eslint-disable */
/**
 * ooo-yay.com API
 * Resource-based API for ooo-yay.com.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FeedAuthorSchema
 */
export interface FeedAuthorSchema {
    /**
     * 
     * @type {string}
     * @memberof FeedAuthorSchema
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FeedAuthorSchema
     */
    url?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FeedAuthorSchema
     */
    avatar?: string | null;
}

/**
 * Check if a given object implements the FeedAuthorSchema interface.
 */
export function instanceOfFeedAuthorSchema(value: object): value is FeedAuthorSchema {
    return true;
}

export function FeedAuthorSchemaFromJSON(json: any): FeedAuthorSchema {
    return FeedAuthorSchemaFromJSONTyped(json, false);
}

export function FeedAuthorSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): FeedAuthorSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'url': json['url'] == null ? undefined : json['url'],
        'avatar': json['avatar'] == null ? undefined : json['avatar'],
    };
}

export function FeedAuthorSchemaToJSON(value?: FeedAuthorSchema | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'url': value['url'],
        'avatar': value['avatar'],
    };
}

