/* tslint:disable */
/* eslint-disable */
/**
 * ooo-yay.com API
 * Resource-based API for ooo-yay.com.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FileMutateMetadata
 */
export interface FileMutateMetadata {
    /**
     * 
     * @type {Array<number>}
     * @memberof FileMutateMetadata
     */
    posts?: Array<number> | null;
}

/**
 * Check if a given object implements the FileMutateMetadata interface.
 */
export function instanceOfFileMutateMetadata(value: object): value is FileMutateMetadata {
    return true;
}

export function FileMutateMetadataFromJSON(json: any): FileMutateMetadata {
    return FileMutateMetadataFromJSONTyped(json, false);
}

export function FileMutateMetadataFromJSONTyped(json: any, ignoreDiscriminator: boolean): FileMutateMetadata {
    if (json == null) {
        return json;
    }
    return {
        
        'posts': json['posts'] == null ? undefined : json['posts'],
    };
}

export function FileMutateMetadataToJSON(value?: FileMutateMetadata | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'posts': value['posts'],
    };
}

