/* tslint:disable */
/* eslint-disable */
/**
 * ooo-yay.com API
 * Resource-based API for ooo-yay.com.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AdminCommentList } from './AdminCommentList';
import {
    AdminCommentListFromJSON,
    AdminCommentListFromJSONTyped,
    AdminCommentListToJSON,
} from './AdminCommentList';

/**
 * 
 * @export
 * @interface PagedAdminCommentList
 */
export interface PagedAdminCommentList {
    /**
     * 
     * @type {Array<AdminCommentList>}
     * @memberof PagedAdminCommentList
     */
    items: Array<AdminCommentList>;
    /**
     * 
     * @type {number}
     * @memberof PagedAdminCommentList
     */
    count: number;
}

/**
 * Check if a given object implements the PagedAdminCommentList interface.
 */
export function instanceOfPagedAdminCommentList(value: object): value is PagedAdminCommentList {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('count' in value) || value['count'] === undefined) return false;
    return true;
}

export function PagedAdminCommentListFromJSON(json: any): PagedAdminCommentList {
    return PagedAdminCommentListFromJSONTyped(json, false);
}

export function PagedAdminCommentListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PagedAdminCommentList {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(AdminCommentListFromJSON)),
        'count': json['count'],
    };
}

export function PagedAdminCommentListToJSON(value?: PagedAdminCommentList | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'items': ((value['items'] as Array<any>).map(AdminCommentListToJSON)),
        'count': value['count'],
    };
}

