/* tslint:disable */
/* eslint-disable */
/**
 * ooo-yay.com API
 * Resource-based API for ooo-yay.com.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Group } from './Group';
import {
    GroupFromJSON,
    GroupFromJSONTyped,
    GroupToJSON,
} from './Group';

/**
 * 
 * @export
 * @interface PagedGroup
 */
export interface PagedGroup {
    /**
     * 
     * @type {Array<Group>}
     * @memberof PagedGroup
     */
    items: Array<Group>;
    /**
     * 
     * @type {number}
     * @memberof PagedGroup
     */
    count: number;
}

/**
 * Check if a given object implements the PagedGroup interface.
 */
export function instanceOfPagedGroup(value: object): value is PagedGroup {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('count' in value) || value['count'] === undefined) return false;
    return true;
}

export function PagedGroupFromJSON(json: any): PagedGroup {
    return PagedGroupFromJSONTyped(json, false);
}

export function PagedGroupFromJSONTyped(json: any, ignoreDiscriminator: boolean): PagedGroup {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(GroupFromJSON)),
        'count': json['count'],
    };
}

export function PagedGroupToJSON(value?: PagedGroup | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'items': ((value['items'] as Array<any>).map(GroupToJSON)),
        'count': value['count'],
    };
}

