/* tslint:disable */
/* eslint-disable */
/**
 * ooo-yay.com API
 * Resource-based API for ooo-yay.com.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PostSummaryForSeries } from './PostSummaryForSeries';
import {
    PostSummaryForSeriesFromJSON,
    PostSummaryForSeriesFromJSONTyped,
    PostSummaryForSeriesToJSON,
} from './PostSummaryForSeries';

/**
 * 
 * @export
 * @interface PagedPostSummaryForSeries
 */
export interface PagedPostSummaryForSeries {
    /**
     * 
     * @type {Array<PostSummaryForSeries>}
     * @memberof PagedPostSummaryForSeries
     */
    items: Array<PostSummaryForSeries>;
    /**
     * 
     * @type {number}
     * @memberof PagedPostSummaryForSeries
     */
    count: number;
}

/**
 * Check if a given object implements the PagedPostSummaryForSeries interface.
 */
export function instanceOfPagedPostSummaryForSeries(value: object): value is PagedPostSummaryForSeries {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('count' in value) || value['count'] === undefined) return false;
    return true;
}

export function PagedPostSummaryForSeriesFromJSON(json: any): PagedPostSummaryForSeries {
    return PagedPostSummaryForSeriesFromJSONTyped(json, false);
}

export function PagedPostSummaryForSeriesFromJSONTyped(json: any, ignoreDiscriminator: boolean): PagedPostSummaryForSeries {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(PostSummaryForSeriesFromJSON)),
        'count': json['count'],
    };
}

export function PagedPostSummaryForSeriesToJSON(value?: PagedPostSummaryForSeries | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'items': ((value['items'] as Array<any>).map(PostSummaryForSeriesToJSON)),
        'count': value['count'],
    };
}

