/* tslint:disable */
/* eslint-disable */
/**
 * ooo-yay.com API
 * Resource-based API for ooo-yay.com.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PostListPublic } from './PostListPublic';
import {
    PostListPublicFromJSON,
    PostListPublicFromJSONTyped,
    PostListPublicToJSON,
} from './PostListPublic';

/**
 * 
 * @export
 * @interface PagedPostListPublic
 */
export interface PagedPostListPublic {
    /**
     * 
     * @type {Array<PostListPublic>}
     * @memberof PagedPostListPublic
     */
    items: Array<PostListPublic>;
    /**
     * 
     * @type {number}
     * @memberof PagedPostListPublic
     */
    count: number;
}

/**
 * Check if a given object implements the PagedPostListPublic interface.
 */
export function instanceOfPagedPostListPublic(value: object): value is PagedPostListPublic {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('count' in value) || value['count'] === undefined) return false;
    return true;
}

export function PagedPostListPublicFromJSON(json: any): PagedPostListPublic {
    return PagedPostListPublicFromJSONTyped(json, false);
}

export function PagedPostListPublicFromJSONTyped(json: any, ignoreDiscriminator: boolean): PagedPostListPublic {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(PostListPublicFromJSON)),
        'count': json['count'],
    };
}

export function PagedPostListPublicToJSON(value?: PagedPostListPublic | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'items': ((value['items'] as Array<any>).map(PostListPublicToJSON)),
        'count': value['count'],
    };
}

