/* tslint:disable */
/* eslint-disable */
/**
 * ooo-yay.com API
 * Resource-based API for ooo-yay.com.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Permission } from './Permission';
import {
    PermissionFromJSON,
    PermissionFromJSONTyped,
    PermissionToJSON,
} from './Permission';

/**
 * 
 * @export
 * @interface PagedPermission
 */
export interface PagedPermission {
    /**
     * 
     * @type {Array<Permission>}
     * @memberof PagedPermission
     */
    items: Array<Permission>;
    /**
     * 
     * @type {number}
     * @memberof PagedPermission
     */
    count: number;
}

/**
 * Check if a given object implements the PagedPermission interface.
 */
export function instanceOfPagedPermission(value: object): value is PagedPermission {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('count' in value) || value['count'] === undefined) return false;
    return true;
}

export function PagedPermissionFromJSON(json: any): PagedPermission {
    return PagedPermissionFromJSONTyped(json, false);
}

export function PagedPermissionFromJSONTyped(json: any, ignoreDiscriminator: boolean): PagedPermission {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(PermissionFromJSON)),
        'count': json['count'],
    };
}

export function PagedPermissionToJSON(value?: PagedPermission | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'items': ((value['items'] as Array<any>).map(PermissionToJSON)),
        'count': value['count'],
    };
}

