/* tslint:disable */
/* eslint-disable */
/**
 * ooo-yay.com API
 * Resource-based API for ooo-yay.com.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AdminUserDetails } from './AdminUserDetails';
import {
    AdminUserDetailsFromJSON,
    AdminUserDetailsFromJSONTyped,
    AdminUserDetailsToJSON,
} from './AdminUserDetails';

/**
 * 
 * @export
 * @interface PagedAdminUserDetails
 */
export interface PagedAdminUserDetails {
    /**
     * 
     * @type {Array<AdminUserDetails>}
     * @memberof PagedAdminUserDetails
     */
    items: Array<AdminUserDetails>;
    /**
     * 
     * @type {number}
     * @memberof PagedAdminUserDetails
     */
    count: number;
}

/**
 * Check if a given object implements the PagedAdminUserDetails interface.
 */
export function instanceOfPagedAdminUserDetails(value: object): value is PagedAdminUserDetails {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('count' in value) || value['count'] === undefined) return false;
    return true;
}

export function PagedAdminUserDetailsFromJSON(json: any): PagedAdminUserDetails {
    return PagedAdminUserDetailsFromJSONTyped(json, false);
}

export function PagedAdminUserDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): PagedAdminUserDetails {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(AdminUserDetailsFromJSON)),
        'count': json['count'],
    };
}

export function PagedAdminUserDetailsToJSON(value?: PagedAdminUserDetails | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'items': ((value['items'] as Array<any>).map(AdminUserDetailsToJSON)),
        'count': value['count'],
    };
}

