/* tslint:disable */
/* eslint-disable */
/**
 * ooo-yay.com API
 * Resource-based API for ooo-yay.com.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CommentList } from './CommentList';
import {
    CommentListFromJSON,
    CommentListFromJSONTyped,
    CommentListToJSON,
} from './CommentList';

/**
 * 
 * @export
 * @interface PagedCommentList
 */
export interface PagedCommentList {
    /**
     * 
     * @type {Array<CommentList>}
     * @memberof PagedCommentList
     */
    items: Array<CommentList>;
    /**
     * 
     * @type {number}
     * @memberof PagedCommentList
     */
    count: number;
}

/**
 * Check if a given object implements the PagedCommentList interface.
 */
export function instanceOfPagedCommentList(value: object): value is PagedCommentList {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('count' in value) || value['count'] === undefined) return false;
    return true;
}

export function PagedCommentListFromJSON(json: any): PagedCommentList {
    return PagedCommentListFromJSONTyped(json, false);
}

export function PagedCommentListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PagedCommentList {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(CommentListFromJSON)),
        'count': json['count'],
    };
}

export function PagedCommentListToJSON(value?: PagedCommentList | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'items': ((value['items'] as Array<any>).map(CommentListToJSON)),
        'count': value['count'],
    };
}

