/* tslint:disable */
/* eslint-disable */
/**
 * ooo-yay.com API
 * Resource-based API for ooo-yay.com.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostCreate
 */
export interface PostCreate {
    /**
     * 
     * @type {string}
     * @memberof PostCreate
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof PostCreate
     */
    content: string;
    /**
     * 
     * @type {Date}
     * @memberof PostCreate
     */
    publishedAt?: Date | null;
    /**
     * 
     * @type {number}
     * @memberof PostCreate
     */
    seriesId?: number | null;
    /**
     * 
     * @type {string}
     * @memberof PostCreate
     */
    slug?: string | null;
}

/**
 * Check if a given object implements the PostCreate interface.
 */
export function instanceOfPostCreate(value: object): value is PostCreate {
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('content' in value) || value['content'] === undefined) return false;
    return true;
}

export function PostCreateFromJSON(json: any): PostCreate {
    return PostCreateFromJSONTyped(json, false);
}

export function PostCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'content': json['content'],
        'publishedAt': json['published_at'] == null ? undefined : (new Date(json['published_at'])),
        'seriesId': json['series_id'] == null ? undefined : json['series_id'],
        'slug': json['slug'] == null ? undefined : json['slug'],
    };
}

export function PostCreateToJSON(value?: PostCreate | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'title': value['title'],
        'content': value['content'],
        'published_at': value['publishedAt'] == null ? undefined : ((value['publishedAt'] as any).toISOString()),
        'series_id': value['seriesId'],
        'slug': value['slug'],
    };
}

