/* tslint:disable */
/* eslint-disable */
/**
 * ooo-yay.com API
 * Resource-based API for ooo-yay.com.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProficiencySchema
 */
export interface ProficiencySchema {
    /**
     * 
     * @type {string}
     * @memberof ProficiencySchema
     */
    category: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ProficiencySchema
     */
    items: Array<string>;
}

/**
 * Check if a given object implements the ProficiencySchema interface.
 */
export function instanceOfProficiencySchema(value: object): value is ProficiencySchema {
    if (!('category' in value) || value['category'] === undefined) return false;
    if (!('items' in value) || value['items'] === undefined) return false;
    return true;
}

export function ProficiencySchemaFromJSON(json: any): ProficiencySchema {
    return ProficiencySchemaFromJSONTyped(json, false);
}

export function ProficiencySchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProficiencySchema {
    if (json == null) {
        return json;
    }
    return {
        
        'category': json['category'],
        'items': json['items'],
    };
}

export function ProficiencySchemaToJSON(value?: ProficiencySchema | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'category': value['category'],
        'items': value['items'],
    };
}

