/* tslint:disable */
/* eslint-disable */
/**
 * ooo-yay.com API
 * Resource-based API for ooo-yay.com.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProficiencySchema } from './ProficiencySchema';
import {
    ProficiencySchemaFromJSON,
    ProficiencySchemaFromJSONTyped,
    ProficiencySchemaToJSON,
} from './ProficiencySchema';
import type { ExperienceSchema } from './ExperienceSchema';
import {
    ExperienceSchemaFromJSON,
    ExperienceSchemaFromJSONTyped,
    ExperienceSchemaToJSON,
} from './ExperienceSchema';

/**
 * 
 * @export
 * @interface ResumeSchema
 */
export interface ResumeSchema {
    /**
     * 
     * @type {string}
     * @memberof ResumeSchema
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ResumeSchema
     */
    githubUrl: string;
    /**
     * 
     * @type {string}
     * @memberof ResumeSchema
     */
    websiteUrl: string;
    /**
     * 
     * @type {string}
     * @memberof ResumeSchema
     */
    bio: string;
    /**
     * 
     * @type {Array<ProficiencySchema>}
     * @memberof ResumeSchema
     */
    proficiencies: Array<ProficiencySchema>;
    /**
     * 
     * @type {Array<ExperienceSchema>}
     * @memberof ResumeSchema
     */
    experiences: Array<ExperienceSchema>;
}

/**
 * Check if a given object implements the ResumeSchema interface.
 */
export function instanceOfResumeSchema(value: object): value is ResumeSchema {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('githubUrl' in value) || value['githubUrl'] === undefined) return false;
    if (!('websiteUrl' in value) || value['websiteUrl'] === undefined) return false;
    if (!('bio' in value) || value['bio'] === undefined) return false;
    if (!('proficiencies' in value) || value['proficiencies'] === undefined) return false;
    if (!('experiences' in value) || value['experiences'] === undefined) return false;
    return true;
}

export function ResumeSchemaFromJSON(json: any): ResumeSchema {
    return ResumeSchemaFromJSONTyped(json, false);
}

export function ResumeSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResumeSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'githubUrl': json['github_url'],
        'websiteUrl': json['website_url'],
        'bio': json['bio'],
        'proficiencies': ((json['proficiencies'] as Array<any>).map(ProficiencySchemaFromJSON)),
        'experiences': ((json['experiences'] as Array<any>).map(ExperienceSchemaFromJSON)),
    };
}

export function ResumeSchemaToJSON(value?: ResumeSchema | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'github_url': value['githubUrl'],
        'website_url': value['websiteUrl'],
        'bio': value['bio'],
        'proficiencies': ((value['proficiencies'] as Array<any>).map(ProficiencySchemaToJSON)),
        'experiences': ((value['experiences'] as Array<any>).map(ExperienceSchemaToJSON)),
    };
}

