/* tslint:disable */
/* eslint-disable */
/**
 * ooo-yay.com API
 * Resource-based API for ooo-yay.com.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SeriesUpdate
 */
export interface SeriesUpdate {
    /**
     * 
     * @type {string}
     * @memberof SeriesUpdate
     */
    title?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SeriesUpdate
     */
    slug?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SeriesUpdate
     */
    description?: string | null;
}

/**
 * Check if a given object implements the SeriesUpdate interface.
 */
export function instanceOfSeriesUpdate(value: object): value is SeriesUpdate {
    return true;
}

export function SeriesUpdateFromJSON(json: any): SeriesUpdate {
    return SeriesUpdateFromJSONTyped(json, false);
}

export function SeriesUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): SeriesUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'] == null ? undefined : json['title'],
        'slug': json['slug'] == null ? undefined : json['slug'],
        'description': json['description'] == null ? undefined : json['description'],
    };
}

export function SeriesUpdateToJSON(value?: SeriesUpdate | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'title': value['title'],
        'slug': value['slug'],
        'description': value['description'],
    };
}

