/* tslint:disable */
/* eslint-disable */
/**
 * ooo-yay.com API
 * Resource-based API for ooo-yay.com.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TokenRefreshOutputSchema
 */
export interface TokenRefreshOutputSchema {
    /**
     * 
     * @type {string}
     * @memberof TokenRefreshOutputSchema
     */
    refresh: string;
    /**
     * 
     * @type {string}
     * @memberof TokenRefreshOutputSchema
     */
    access: string | null;
}

/**
 * Check if a given object implements the TokenRefreshOutputSchema interface.
 */
export function instanceOfTokenRefreshOutputSchema(value: object): value is TokenRefreshOutputSchema {
    if (!('refresh' in value) || value['refresh'] === undefined) return false;
    if (!('access' in value) || value['access'] === undefined) return false;
    return true;
}

export function TokenRefreshOutputSchemaFromJSON(json: any): TokenRefreshOutputSchema {
    return TokenRefreshOutputSchemaFromJSONTyped(json, false);
}

export function TokenRefreshOutputSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): TokenRefreshOutputSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'refresh': json['refresh'],
        'access': json['access'],
    };
}

export function TokenRefreshOutputSchemaToJSON(value?: TokenRefreshOutputSchema | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'refresh': value['refresh'],
        'access': value['access'],
    };
}

